var minRange = 1940, 
    maxRange = 1990,
    lowerBound = 1920,
    upperBound = 2010,
    director,
    map,
    layer,
    table = "1x8noYJ9JEr0g3ObbFG03cT9VbsRgAVpcyqbqS8k";
    
$(function() { // initialize maps + sidebar ()
    
    $('#min').text(lowerBound);
    $('#max').text(upperBound);
    
    map = new google.maps.Map(document.getElementById('map-canvas'), {
        center: new google.maps.LatLng(37.78217505967539, -122.41824985581053),
        zoom: 13,
        streetViewControl: true,
        streetViewControlOptions: {
            position: google.maps.ControlPosition.LEFT_TOP
        },        
        zoomControl: true,
        zoomControlOptions: {
          position: google.maps.ControlPosition.LEFT_TOP
        },
        scaleControl: false,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });
    
    layer = new google.maps.FusionTablesLayer({
        query: {
            select: "location",
            from: "1x8noYJ9JEr0g3ObbFG03cT9VbsRgAVpcyqbqS8k",
            where: "col1>="+minRange+" and col1<="+maxRange
        },
        map: map,
        styleId: 5,
        templateId: 4
    });
    
    // Set first tab active by default 
    $( "#tabs" ).tabs();
    
    // Toggle sidebar and hide icons at launch
    $("#sidebar-minimized").hide();
    $(".expand-btn, .collapse-btn").bind('click', function() {
        $("#sidebar").toggle();
        $("#sidebar-minimized").toggle();
    });
});

$(function() {
    $( "#slider-range" ).slider({
        range: true,
        min: lowerBound,
        max: upperBound,
        change: updateMap,        
        values: [ minRange, maxRange ],
        slide: function( event, ui ) {
            $( "#amount" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] );
        }
    });
    $( "#amount" ).val($( "#slider-range" ).slider( "values", 0 ) +
      " - " + $( "#slider-range" ).slider( "values", 1 ) );
});

function updateMap() {
    minRange = $( "#slider-range" ).slider( "values", 0 );
    maxRange = $( "#slider-range" ).slider( "values", 1 );
    layer.setMap(); // clears markers
    layer = new google.maps.FusionTablesLayer({
        query: {
            select: "location",
            from: "1x8noYJ9JEr0g3ObbFG03cT9VbsRgAVpcyqbqS8k",
            where: "col1>="+minRange+" and col1<="+maxRange
        },
        map: map,
        styleId: 5,
        templateId: 4
    });
}

$(function() { // instantiate director names for autocomplete
    var availableNames = [
        "Michael Ferris Gibson",
        "Walter Hill",
        "Peter Segal",
        "Charles Chaplin",
        "Lina Wertmuller",
        "Keith Samples",
        "John Glen",
        "W.S. Van Dyke",
        "Henry King",
        "Joseph L. Mankiewicz",
        "George Lucas",
        "Brian Ging",
        "John Jacobsen",
        "John DeBello",
        "Thomas Balmes",
        "Howard Hawks",
        "Paul Verhoeven",
        "Garry Marshall",
        "Harold Ramis",
        "Scott McGehee",
        "Chris Columbus",
        "John Carpenter",
        "John Frankenheimer",
        "Robert Iscove",
        "Peter Yates",
        "Hugh Wilson",
        "Harriet Dodge & Silas Howard",
        "Nancy Walker",
        "Brian DePalma",
        "Wayne Wang",
        "Finn Taylor",
        "David Lowell Rich",
        "Brad Silberling",
        "Michael Apted",
        "Rob Epstein",
        "Paul Barnett",
        "Jon Amiel",
        "Louis Malle",
        "Rudolph Mate",
        "Delmer Daves",
        "Blake Edwards",
        "Barbet Schroeder",
        "Don Siegel",
        "Betty Thomas",
        "Mark Decena",
        "David S. Ward",
        "Steve Carr",
        "Tiffanie DeBartolo",
        "Joel Schumacher",
        "Ron Howard",
        "Donald Siegel",
        "Conan Le Cilaire",
        "Alfred Hitchcock",
        "Nicholas Tucker",
        "Roland Joffe",
        "Ivan Reitman",
        "Peter Weir",
        "Phil Joanou",
        "Henry Koster",
        "Les Mayfield",
        "Robert Zemeckis",
        "Michael Lehmann",
        "Colin Higgins",
        "Richard Rush",
        "Raoul Walsh",
        "Sam Weisman",
        "Howard Deutch",
        "John Madden",
        "Eric von Stroheim",
        "Greg Harrison",
        "Stanley Kramer",
        "Jakob Kornbluth & Josh Kornbluth",
        "Dennis Dugan",
        "Larry Peerce",
        "Hal Ashby",
        "Tomas Gislason",
        "John Byrum",
        "Bruce Humberstone",
        "Robert Stevenson",
        "Mel Brooks",
        "Carl Franklin",
        "David R. Ellis",
        "Vadim Perelman",
        "Kevin Rodney Sullivan",
        "Ang Lee",
        "George Stevens",
        "Steven Spielberg",
        "Joe Dante",
        "Neil Jordan",
        "Philip Kaufman",
        "Robert Gordon",
        "Francis Ford Coppola",
        "William Friedkin",
        "Richard Marquand",
        "Henry Selick",
        "James Nguyen",
        "Mark Waters",
        "Alan Jacobs",
        "Juliet Bashore",
        "Vicky Funari",
        "Ted Post",
        "Paul Aaron",
        "Thomas Carter",
        "David Miller",
        "Gus Van Sant",
        "Loren Marsh",
        "Mike Newell",
        "Albert Brooks",
        "Marc Rocco",
        "Sean A.F. Scott",
        "Hassan Zee",
        "Vincent Sherman",
        "John Schlesinger",
        "George Sidney",
        "Mario Van Peebles",
        "Tom Shadyac",
        "Paul Schrader",
        "Richard Lester",
        "Jon Turteltaub",
        "Herbert Ross",
        "Matthew Huffman",
        "George Seaton",
        "John Boorman",
        "Thomas Michael Donnelly",
        "Doug Pray",
        "John McTiernan",
        "Andrzej Bartkowiak",
        "Andrew Lau",
        "Peter Chelsom",
        "Bill Persky",
        "Paul Lazarus",
        "Wolfgang Petersen",
        "Alan Parker",
        "Emile Ardolino",
        "Bill Duke",
        "Phil Alden Robinson",
        "Thomas Schlamme",
        "Barry Levinson",
        "Nicholas Meyer",
        "Leonard Nimoy",
        "Rupert Wainwright",
        "Jenny Bowen",
        "Clint Eastwood",
        "Richard Donner",
        "Pat O'Connor",
        "Martin Guigui",
        "Charles Barton",
        "Woody Allen",
        "Niels Mueller",
        "Gary Sinyor",
        "Eric Steel",
        "Edward Dmytryk",
        "Jonathan Parker",
        "Michael Ritchie",
        "Joel Oliansky",
        "John Amiel",
        "Buddy Van Horn",
        "Randa Haines",
        "Oliver Stone",
        "James Fargo",
        "Tony Scott",
        "Errol Morris",
        "David Fincher",
        "Mike Nichols",
        "Robert Wise",
        "Alan Crosland",
        "Orson Welles",
        "Martin Jay Sadoff",
        "Stuart Rosenberg",
        "John Huston",
        "The Wachowski Brothers",
        "Irwin Winkler",
        "Don Medford",
        "Nancy Meyers",
        "Peter Hyams",
        "Steven Conrad",
        "Michael Bay",
        "Roger Kumble",
        "Cecil B. DeMille",
        "John Guillermin",
        "Adam Shankman",
        "Gene Wilder",
        "Gordon Douglas",
        "Douglas Day Stewart",
        "Ron Shelton",
        "Joseph Ruben",
        "Eric G. Johnson",
        "Audrey Wells",
        "Wim Wenders",
        "Phillip R. Ford",
        "Vincent Ward",
        "William Arntz",
        "Peter Bogdanovich",
        "Luis Mandoki",
        "Norman Foster",
        "Fina Torres",
        "Melville Shavelson",
        "Alexander Bulkley"
    ];
    $( "#directors" ).autocomplete({
        source: availableNames,
        minLength: 1,
        select: function( event, ui) {
            director = ui.item.value;
        },
        change: updateDirMap
    });
});

$(function() { // instantiate titles for autocomplete
    var availableTitles = [
        "24 Hours on Craigslist",
        "48 Hours",
        "50 First Dates",
        "A Jitney Elopement",
        "A Night Full of Rain",
        "A Smile Like Yours",
        "A View to a Kill",
        "After the Thin Man",
        "Alexander's Ragtime Band",
        "All About Eve",
        "American Graffiti",
        "American Yearbook",
        "Another 48 Hours",
        "Around the Fire",
        "Attack of the Killer Tomatoes",
        "Babies",
        "Barbary Coast",
        "Basic Instinct",
        "Beaches",
        "Bedazzled",
        "Bee Season",
        "Bicentennial Man",
        "Big Touble in Lttle China",
        "Birdman of Alcatraz",
        "Boys and Girls",
        "Bullitt",
        "Burglar",
        "By Hook or By Crook",
        "Can't Stop the Music",
        "Casualties of War",
        "Chan is Missing",
        "Cherish",
        "Chu Chu and the Philly Flash",
        "City of Angels",
        "Class Action",
        "Common Threads: Stories From the Quilt",
        "Confessions of a Burning Man",
        "Copycat",
        "Crackers",
        "D.O.A",
        "Dark Passage",
        "Days of Wine and Roses",
        "Desperate Measures",
        "Dim Sum: A Little Bit of Heart",
        "Dirty Harry",
        "Doctor Doolittle",
        "Dopamine",
        "Down Periscope",
        "Dr. Doolittle 2",
        "Dream for an Insomniac",
        "Dream with the Fishes",
        "Dying Young",
        "Edtv",
        "Escape From Alcatraz",
        "Experiment in Terror",
        "Faces of Death",
        "Family Plot",
        "Fandom",
        "Fat Man and Little Boy",
        "Fathers' Day",
        "Fearless",
        "Final Analysis",
        "Flower Drum Song",
        "Flubber",
        "Forrest Gump",
        "Forty Days and Forty Nights",
        "Foul Play",
        "Freebie and the Bean",
        "Gentleman Jim",
        "George of the Jungle",
        "Getting Even with Dad",
        "Golden Gate",
        "Greed",
        "Groove",
        "Guess Who's Coming to Dinner",
        "Haiku Tunnel",
        "Happy Gilmore",
        "Hard to Hold",
        "Harold and Maude",
        "Heart and Souls",
        "Heart Beat",
        "Hello Frisco, Hello",
        "Herbie Rides Again",
        "High Anxiety",
        "High Crimes",
        "Homeward Bound II: Lost in San Francisco",
        "House of Sand and Fog",
        "How Stella Got Her Groove Back",
        "Hulk",
        "I Remember Mama",
        "Indiana Jones and the Last Crusade",
        "Innerspace",
        "Interview With The Vampire",
        "Invasion of the Body Snatchers",
        "It Came From Beneath the Sea",
        "Jack",
        "Jade",
        "Jagged Edge",
        "James and the Giant Peach",
        "Joy Luck Club",
        "Julie and Jack",
        "Junior",
        "Just Like Heaven",
        "Just One Night",
        "Kamikaze Hearts",
        "Live Nude Girls Unite",
        "Magnum Force",
        "Marnie",
        "Maxie",
        "Memoirs of an Invisible Man",
        "Metro",
        "Midnight Lace",
        "Milk",
        "Mission (aka City of Bars)",
        "Mona Lisa Smile",
        "Mother",
        "Mrs. Doubtfire",
        "Murder in the First",
        "Never Die Twice",
        "Night of Henna",
        "Nina Takes a Lover",
        "Nine Months",
        "Nine to Five",
        "Nora Prentiss",
        "On the Beach",
        "Pacific Heights",
        "Pal Joey",
        "Panther",
        "Patch Adams",
        "Patty Hearst",
        "Petulia",
        "Phenomenon",
        "Play it Again, Sam",
        "Playing Mona Lisa",
        "Pleasure of His Company",
        "Point Blank",
        "Pretty Woman",
        "Psych-Out",
        "Quicksilver",
        "Raising Cain",
        "Red Diaper Baby",
        "Rent",
        "Rollerball",
        "Romeo Must Die",
        "San Francisco",
        "Sausalito",
        "Serendipity",
        "Serial",
        "Seven Girlfriends",
        "Shadow of the Thin Man",
        "Shattered",
        "Shoot the Moon",
        "Sister Act",
        "Sister Act 2: Back in the Habit",
        "Sneakers",
        "So I Married an Axe Murderer",
        "Sphere",
        "Star Trek II : The Wrath of Khan",
        "Star Trek IV: The Voyage Home",
        "Star Trek VI: The Undiscovered County",
        "Stigmata",
        "Street Music",
        "Sudden Fear",
        "Sudden Impact",
        "Superman",
        "Susan Slade",
        "Sweet November",
        "Swing",
        "Swingin' Along",
        "Take the Money and Run",
        "The Assassination of Richard Nixon",
        "The Bachelor",
        "The Birds",
        "The Bridge",
        "The Caine Mutiny",
        "The Californians",
        "The Candidate",
        "The Competiton",
        "The Conversation",
        "The Core",
        "The Dead Pool",
        "The Doctor",
        "The Doors",
        "The Enforcer",
        "The Fan",
        "The Fog of War",
        "The Game",
        "The Graduate",
        "The House on Telegraph Hill",
        "The Jazz Singer",
        "The Lady from Shanghai",
        "The Last of the Gladiators",
        "The Laughing Policeman",
        "The Lineup",
        "The Love Bug",
        "The Maltese Falcon",
        "The Matrix",
        "The Net",
        "The Nightmare Before Christmas",
        "The Organization",
        "The Other Sister",
        "The Parent Trap",
        "The Presidio",
        "The Princess Diaries",
        "The Pursuit of Happyness",
        "The Right Stuff",
        "The Rock",
        "The Sweetest Thing",
        "The Ten Commandments",
        "The Times of Harvey Milk",
        "The Towering Inferno",
        "The Wedding Planner",
        "The Woman In Red",
        "They Call Me MISTER Tibbs",
        "Thief of Hearts",
        "Time After Time",
        "Tin Cup",
        "To the Ends of the Earth",
        "True Believer",
        "Tucker: The Man and His Dreams",
        "Tweek City",
        "Twisted",
        "Under the Tuscan Sun",
        "Until the End of the World",
        "Vegas in Space",
        "Vertigo",
        "What Dreams May Come",
        "What the Bleep Do We Know",
        "What's Up Doc?",
        "When a Man Loves a Woman",
        "Woman on the Run",
        "Woman on Top",
        "Yours, Mine and Ours",
        "Zodiac",
        "The Zodiac"
    ];
    $( "#titles" ).autocomplete({
        source: availableTitles,
        minLength: 1,
        select: function( event, ui) {
            title = ui.item.value;
        },
        change: updateTitleMap
    });
});

function updateTitleMap() {
    console.log("value: " + title);
    layer.setMap(); // clears markers
    layer = new google.maps.FusionTablesLayer({
        query: {
            select: "location",
            from: "1x8noYJ9JEr0g3ObbFG03cT9VbsRgAVpcyqbqS8k",
            where: "Title='" + title + "'"
        },
        map: map,
        styleId: 5, // 1-3=Red Circle, 4-6=Blue Pin
        templateId: 4
    });
}    

function updateDirMap() {
    console.log("value: " + director);
    layer.setMap(); // clears markers
    layer = new google.maps.FusionTablesLayer({
        query: {
            select: "location",
            from: "1x8noYJ9JEr0g3ObbFG03cT9VbsRgAVpcyqbqS8k",
            where: "col7 in ('" + director + "')"
        },
        map: map,
        styleId: 5, // 1-3=Red Circle, 4-6=Blue Pin
        templateId: 4
    });
}